server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/native-file-repo
        git:
          uri: https://github.com/hyensukim/spring-cloud-config-test.git
#          uri: file://C:/git-local-repo
#          username: [username] - private repo 인 경우 설정
#          password: [password] - private repo 인 경우 설정
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
